[package]
name = "connect4"
version = "0.1.0"
authors = ["Valdemar Ceccon <valdemar.ceccon@gmail.com>"]
edition = "2018"

[lib]
name="connect4_core"
path="src/lib.rs"

[[bin]]
name="connect4_cli"
path="src/bin/main.rs"

[dependencies]
colored = "2"
